name: music_py
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - matplotlib=3.7.2
  - notebook
  - numpy=1.26.4
  - opentsne
  - pandas
  - pip
  - pyarrow
  - scipy
  - seaborn
  - tqdm
  - uproot
